name: myapp-compose

services:

  frontend:
    image: ghcr.io/vartanchik12/myapp:latest
    container_name: frontend
    ports:
      - "8181:80"
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: postgres:15
    container_name: mydb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - mynet

volumes:
  dbdata:

networks:
  mynet:

